/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormFavAddReq struct {
	// 商品ID
	GoodId int64 `json:"good_id"`
	// skuId
	SkuId int64 `json:"sku_id"`
}
