/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormMallFormFavNumRes struct {
	// 收藏总数量
	TotalCount int64 `json:"total_count,omitempty"`
}
