/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormAddressDeleteReq struct {
	// 收货地址ID
	AddressId int64 `json:"address_id"`
}
