/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 获取支付方式
type XbuyAppFormMallFormPaymentMethodGetReq struct {
	PrepayId string `json:"prepay_id"`
}
