/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoStatistics struct {
	SalesVolume float64 `json:"sales_volume,omitempty"`
	OrderCount int32 `json:"order_count,omitempty"`
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	Roi float64 `json:"roi,omitempty"`
}
