/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormMemberNewRegisterReq struct {
	Id int64 `json:"id,omitempty"`
	// 帐号
	Username string `json:"username"`
	// 密码
	Password string `json:"password,omitempty"`
	// 真实姓名
	Realname string `json:"realname,omitempty"`
	// 头像
	Avatar string `json:"avatar,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 验证码
	Code string `json:"code,omitempty"`
	// 手机号码
	Mobile string `json:"mobile,omitempty"`
	// 权限
	Role int32 `json:"role,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 修改时间
	UpdatedAt string `json:"updated_at,omitempty"`
}
