/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetMemberTagListRes struct {
	// 标签ID
	TagId int64 `json:"tag_id,omitempty"`
	// 标签名称
	TagName string `json:"tag_name,omitempty"`
	CreateTime *ModelInterface `json:"create_time,omitempty"`
	// 店铺ID
	ShopId int64 `json:"shop_id,omitempty"`
}
