/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGroupResourceListReq struct {
	// 分组编号
	ResGroupId int64 `json:"res_group_id,omitempty"`
}
