/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200133Data struct {
	// 运费模板编号
	FareId int64 `json:"fare_id,omitempty"`
}
