/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormDeleteMemberGroupRelationRes struct {
	GroupId int64 `json:"group_id,omitempty"`
	UserId int64 `json:"user_id,omitempty"`
}
