/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoSitemapContent struct {
	Submitted int64 `json:"submitted,omitempty"`
	Type_ string `json:"type,omitempty"`
}
