/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormSaveReq struct {
	// 店铺ID
	ShopId int64 `json:"shop_id"`
	// 配置名称
	Name string `json:"name"`
	// 语言
	Lang string `json:"lang"`
	// 配置
	Config string `json:"config"`
	// 是否默认
	IsDefault int32 `json:"is_default"`
}
