/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormUserBuyRes struct {
	// 用户购买力排行前10
	UserBuyList map[string]float64 `json:"user_buy_list,omitempty"`
}
