/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormBindMemberGradeReq struct {
	MemberId int64 `json:"MemberId"`
	GradeId int64 `json:"GradeId"`
	IsAuto int64 `json:"is_auto,omitempty"`
}
