/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormMallFormReviewAddRes struct {
	// 评论编号
	ReviewId int32 `json:"review_id,omitempty"`
}
