/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormServiceDetailReq struct {
	// 服务ID
	ServiceId int64 `json:"service_id"`
}
