/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoOutputValue struct {
	// 属性值编号
	ValueId int64 `json:"value_id,omitempty"`
	// 类型值
	PropValue string `json:"prop_value,omitempty"`
	// 类型图片
	ImgUrl string `json:"img_url,omitempty"`
	ViewId int64 `json:"view_id,omitempty"`
	// 是否是ai
	Ai int32 `json:"ai,omitempty"`
}
