/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyEtcOtherInfo struct {
	Title string `json:"title,omitempty"`
	Body string `json:"body,omitempty"`
}
