/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 获取用户购物车商品数量
type XbuyAppFormMallFormCartNumReq struct {
}
