/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormScatsList struct {
	// 公共分类ID
	Cid int64 `json:"cid,omitempty"`
	// 公共分类名称
	Name string `json:"name,omitempty"`
}
