/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormMallFormMallMemberChangePassWordRes struct {
	// 结果
	Result string `json:"result,omitempty"`
}
