/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormSubmemberEditReq struct {
	Id int64 `json:"id,omitempty"`
	// 父级账号
	Pmemberid int64 `json:"pmemberid,omitempty"`
	// 岗位ID
	PostIds []int64 `json:"postIds"`
	// 部门ID
	DeptId int64 `json:"dept_id"`
	// 帐号
	Username string `json:"username"`
	// 密码
	Password string `json:"password,omitempty"`
	// 真实姓名
	Realname string `json:"realname,omitempty"`
	// 头像
	Avatar string `json:"avatar,omitempty"`
	// 性别[0:未知;1:男;2:女]
	Sex string `json:"sex,omitempty"`
	// qq
	Qq string `json:"qq,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 生日
	Birthday string `json:"birthday,omitempty"`
	// 省
	ProvinceId int32 `json:"province_id,omitempty"`
	// 城市
	CityId int32 `json:"city_id,omitempty"`
	// 地区
	AreaId int32 `json:"area_id,omitempty"`
	// 默认地址
	Address string `json:"address,omitempty"`
	// 手机号码
	Mobile string `json:"mobile,omitempty"`
	// 家庭号码
	HomePhone string `json:"home_phone,omitempty"`
	// 钉钉机器人token
	DingtalkRobotToken string `json:"dingtalk_robot_token,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 修改时间
	UpdatedAt string `json:"updated_at,omitempty"`
}
