/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyEtcAllowMerchant struct {
	Limit int64 `json:"limit,omitempty"`
	Title string `json:"title,omitempty"`
}
