/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodListReq struct {
	// 当前页码
	Page int32 `json:"page,omitempty"`
	// 每页数量
	Limit int32 `json:"limit,omitempty"`
	ViewId int64 `json:"view_id,omitempty"`
	ShopId int64 `json:"shop_id,omitempty"`
	// 标题关键词
	Title string `json:"title,omitempty"`
	OnShelves int32 `json:"on_shelves,omitempty"`
	IsGift int32 `json:"is_gift,omitempty"`
}
