/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse2001Data struct {
	AfterSaleId string `json:"after_sale_id,omitempty"`
	Status string `json:"Status,omitempty"`
}
