/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 添加购物车
type XbuyAppFormMallFormCartAddReq struct {
	GoodId int64 `json:"good_id"`
	SkuId int64 `json:"sku_id"`
	Num int32 `json:"num"`
}
