/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoSkuDetail struct {
	// 规格编号
	SkuId int64 `json:"sku_id,omitempty"`
	// 店铺编号
	ShopId int64 `json:"shop_id,omitempty"`
	// 所属商品编号
	GoodId int64 `json:"good_id,omitempty"`
	// 1:2;2:3=颜色id:红色id;尺寸id:大id
	PropsIds string `json:"props_ids,omitempty"`
	// 价格
	Price float64 `json:"price,omitempty"`
	// 库存
	StockNum int32 `json:"stock_num,omitempty"`
	// 外部编码
	OutId string `json:"out_id,omitempty"`
	// 条码
	Barcode string `json:"barcode,omitempty"`
	// 税率
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 规格图片
	SkuImage string `json:"sku_image,omitempty"`
	// 是否非卖品,默认0(不是),1(是)
	IsForSale int32 `json:"is_for_sale,omitempty"`
	Stocks []XbuyAppDaoStock `json:"stocks,omitempty"`
	Attrs []XbuyAppDaoSkuAttr `json:"attrs,omitempty"`
	Title string `json:"title,omitempty"`
}
