/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormVerifyPhoneApplyReq struct {
	PhoneCountryCode string `json:"phone_country_code,omitempty"`
	Phone string `json:"phone,omitempty"`
}
