/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormCloseShopViewAutoTransReq struct {
	// 商店id
	ShopId int64 `json:"shop_id,omitempty"`
	// 视图id
	ViewId int64 `json:"view_id,omitempty"`
}
