/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormUpdateReceiverInfoReq struct {
	OrderId string `json:"order_id"`
	LastName string `json:"last_name,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	Country string `json:"country,omitempty"`
	State string `json:"state,omitempty"`
	City string `json:"city,omitempty"`
	Street string `json:"street,omitempty"`
	Apartment string `json:"apartment,omitempty"`
	ZipCode string `json:"zip_code,omitempty"`
	IdName string `json:"id_name,omitempty"`
	IdNumber string `json:"id_number,omitempty"`
}
