/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200112Data struct {
	// 会员ID
	MemberId int64 `json:"member_id,omitempty"`
	// 标签ID
	TagId int64 `json:"tag_id,omitempty"`
}
