/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200117Data struct {
	// 菜单ID
	Id int64 `json:"id,omitempty"`
	// 父菜单ID
	Pid int64 `json:"pid,omitempty"`
	// 菜单名称
	Name string `json:"name,omitempty"`
	// 菜单编码
	Code string `json:"code,omitempty"`
	// 菜单图标
	Icon string `json:"icon,omitempty"`
	// 菜单类型（M目录 C菜单 F按钮）
	Type_ string `json:"type,omitempty"`
	// 权限标识
	Perms string `json:"perms,omitempty"`
	// 路由地址
	Path string `json:"path,omitempty"`
	// 组件路径
	Component string `json:"component,omitempty"`
	// 路由参数
	Query string `json:"query,omitempty"`
	// 是否内嵌
	IsFrame string `json:"is_frame,omitempty"`
	// 是否不缓存
	IsCache string `json:"is_cache,omitempty"`
	// 是否隐藏
	IsVisible string `json:"is_visible,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 级别
	Level int32 `json:"level,omitempty"`
	// 树
	Tree string `json:"tree,omitempty"`
	// 排序
	Sort int32 `json:"sort,omitempty"`
	// 菜单状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt string `json:"updated_at,omitempty"`
	// 授权的资源分组列表
	ResGroups []XbuyAppModelEntitySysResourceGroups `json:"res_groups,omitempty"`
}
