/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGroupBatchAddResourceReq struct {
	// 分组编号
	ResGroupId int64 `json:"res_group_id,omitempty"`
	// 资源编号列表
	ResourceIds []int64 `json:"resource_ids,omitempty"`
}
