/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 获取管理后台的登录用户信息
type XbuyAppFormAdminFormMemberInfoReq struct {
}
