/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetMemberRemarkListByMemberIdReq struct {
	MemberId int64 `json:"MemberId"`
	ShopId int64 `json:"ShopId"`
}
