/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200129Data struct {
	QuoteCurrency []string `json:"quote_currency,omitempty"`
	PaymentSupportedCurrency []string `json:"payment_supported_currency,omitempty"`
}
