/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallUploads struct {
	// 自增id
	Id int64 `json:"id,omitempty"`
	// 商品id;1：默认附件表上传，2：装修：3商品类目
	GoodId int64 `json:"good_id,omitempty"`
	// 门店id
	ShopId int64 `json:"shop_id,omitempty"`
	// 用户id
	UserId int64 `json:"user_id,omitempty"`
	// 图片名称
	Name string `json:"name,omitempty"`
	// 图片地址
	Path string `json:"path,omitempty"`
	// 文件类型
	ContentType string `json:"content_type,omitempty"`
	// 原文件名称
	RealName string `json:"real_name,omitempty"`
	// 上传方式
	OssType string `json:"oss_type,omitempty"`
	// 上传时间
	CreateTime string `json:"create_time,omitempty"`
}
