/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormMallFormMallMemberProfileRes struct {
	// 用户ID
	MemberId int64 `json:"member_id,omitempty"`
	// 用户邮箱
	Email string `json:"email,omitempty"`
	// 名
	FirstName string `json:"first_name,omitempty"`
	// 姓
	LastName string `json:"last_name,omitempty"`
	// 用户昵称
	Nick string `json:"nick,omitempty"`
	// 用户手机号
	Phone string `json:"phone,omitempty"`
	// 用户头像
	Avatar string `json:"avatar,omitempty"`
	// 注册时间
	CreateTime string `json:"create_time,omitempty"`
	// 注册IP
	LastIp string `json:"last_ip,omitempty"`
}
