/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormOrderMoneyReq struct {
	// 店铺ID
	ShopId int32 `json:"shop_id,omitempty"`
}
