/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormGoodAddRes struct {
	// 商品编号
	GoodId int64 `json:"good_id,omitempty"`
}
