/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormAfterSaleSkuInfo struct {
	SkuId string `json:"sku_id,omitempty"`
	Num int32 `json:"num,omitempty"`
}
