/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200176Data struct {
	// 7天内付款订单金额
	OrderMoneyList map[string]float64 `json:"order_money_list,omitempty"`
	// 当天付款订单金额
	OrderMoneyTodayList map[string]float64 `json:"order_money_today_list,omitempty"`
}
