/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormSceneInfo struct {
	DeviceId string `json:"device_id,omitempty"`
	H5SceneType string `json:"h5_scene_type,omitempty"`
	H5AppName string `json:"h5_app_name,omitempty"`
	PaidReturnUrl string `json:"paid_return_url,omitempty"`
	CancelReturnUrl string `json:"cancel_return_url,omitempty"`
}
