/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormArticleGetReq struct {
	// 文章ID
	ArticleId int64 `json:"article_id,omitempty"`
}
