/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormRoleDynamicMeta struct {
	// 菜单标题
	Title string `json:"title,omitempty"`
	// 菜单图标
	Icon string `json:"icon,omitempty"`
	// 是否缓存
	NoCache bool `json:"noCache,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
}
