/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormSkuSubAddParam struct {
	// sku_id
	SkuId int64 `json:"sku_id,omitempty"`
	// 税率
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 规格图片
	SkuImage string `json:"sku_image,omitempty"`
	// 规格ID和规格值ID
	PropIds []XbuyAppFormAdminFormSkuSubAddParamPropIds `json:"prop_ids,omitempty"`
}
