/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200205Data struct {
	PrepayId string `json:"prepay_id,omitempty"`
	ExpireIn int32 `json:"expire_in,omitempty"`
}
