/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodInfoListReq struct {
	// 标准类目Id
	Cid int64 `json:"cid"`
	// 标准类目参数ID
	InfoId int64 `json:"info_id,omitempty"`
}
