/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse20018Data struct {
	Level int32 `json:"level,omitempty"`
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	TechnicalSupport *XbuyEtcTechnicalSupport `json:"technical_support,omitempty"`
	DomainBinding *XbuyEtcDomainBinding `json:"domain_binding,omitempty"`
	AllowStores *XbuyEtcAllowStores `json:"allow_stores,omitempty"`
	AllowMerchant *XbuyEtcAllowMerchant `json:"allow_merchant,omitempty"`
	DepartmentAuthority *XbuyEtcDepartmentAuthority `json:"department_authority,omitempty"`
	CopyrightLink *XbuyEtcCopyrightLink `json:"copyright_link,omitempty"`
	SaasModel *XbuyEtcSaasModel `json:"saas_model,omitempty"`
	AllowCustomMade *XbuyEtcAllowCustomMade `json:"allow_custom_made,omitempty"`
	OtherInfo *XbuyEtcOtherInfo `json:"other_info,omitempty"`
}
