/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 售后单列表
type XbuyAppFormMallFormSalesOrderListReq struct {
	OrderId string `json:"order_id"`
}
