/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodAddReq struct {
	// 类目编号
	CatId int64 `json:"cat_id"`
	// 商品编号
	GoodId int64 `json:"good_id,omitempty"`
	// 来源平台
	FromPlatform string `json:"from_platform,omitempty"`
	// 来源平台商品id
	FromGoodId int64 `json:"from_good_id,omitempty"`
	// 商店视图
	ViewId int64 `json:"view_id,omitempty"`
	// 所属门店
	ShopId int64 `json:"shop_id"`
	// 商品标准类目
	Cid int64 `json:"cid"`
	// 商品标题
	Title string `json:"title"`
	// 商品描述
	Desc string `json:"desc,omitempty"`
	// 商品备注
	Note string `json:"note,omitempty"`
	// 商品视频
	VideoUrl string `json:"video_url,omitempty"`
	// 商品主图
	ImageUrl string `json:"image_url,omitempty"`
	// 商品主图
	ImageUrl1 string `json:"image_url_1,omitempty"`
	// 商品主图
	ImageUrl2 string `json:"image_url_2,omitempty"`
	// 商品主图
	ImageUrl3 string `json:"image_url_3,omitempty"`
	// 商品主图
	ImageUrl4 string `json:"image_url_4,omitempty"`
	// 商品别名
	Slug string `json:"slug,omitempty"`
	// 上下架标识,1为上架,2为下架
	OnShelves int32 `json:"on_shelves"`
	// 商品参数值
	GoodInfoValues []XbuyAppFormAdminFormGoodInfoValuesAdd `json:"good_info_values,omitempty"`
	// 文件上传临时ID
	TmpIdminLength10 int64 `json:"tmp_id|min-length:10,omitempty"`
	// 副标题
	SubTitle string `json:"sub_title,omitempty"`
	// 商品重量
	Weight float64 `json:"weight,omitempty"`
	// 是否赠品
	IsGift int32 `json:"is_gift,omitempty"`
	// 是否启用ai翻译
	Ai int32 `json:"ai,omitempty"`
}
