/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityAdminSubmemberShop struct {
	// 子账户ID
	SubmemberId int64 `json:"submember_id,omitempty"`
	// 店铺ID
	ShopId int64 `json:"shop_id,omitempty"`
}
