/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormUpdatePayerInfoReq struct {
	PrepayId string `json:"prepay_id"`
	IdName string `json:"id_name"`
	IdNumber string `json:"id_number"`
}
