/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 订单支付
type XbuyAppFormMallFormOrderPayReq struct {
	SceneType string `json:"scene_type"`
	PickUpOrder bool `json:"pick_up_order,omitempty"`
	PrepayId string `json:"prepay_id"`
	SceneInfo *XbuyAppFormMallFormSceneInfo `json:"scene_info,omitempty"`
	PayWayId string `json:"pay_way_id"`
	CredentialId string `json:"credential_id"`
	Currency string `json:"currency"`
}
