/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200149Data struct {
	WarehouseId int32 `json:"warehouse_id,omitempty"`
	Weight int32 `json:"weight,omitempty"`
}
