/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 发送邮件
type XbuyAppFormAdminFormEmailSendReq struct {
	Recipient string `json:"recipient"`
	Subject string `json:"subject"`
	Content string `json:"content"`
	Attachment []string `json:"attachment,omitempty"`
}
