/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormArticlesCatSubAddRes struct {
	// 类目id
	CatId int64 `json:"cat_id,omitempty"`
}
