/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormAfterSalesApplyRes struct {
	OrderId string `json:"order_id,omitempty"`
	Status string `json:"status,omitempty"`
}
