/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse20057Data struct {
	// 验证码ID
	Cid string `json:"cid,omitempty"`
	// 验证码
	Base64 string `json:"base64,omitempty"`
}
