/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormCartDetail struct {
	// 主键id
	Id int32 `json:"id,omitempty"`
	// 所属用户
	MemberId int64 `json:"member_id,omitempty"`
	// 所属商品规格属性
	SkuId int64 `json:"sku_id,omitempty"`
	// 商品数量
	Num int32 `json:"num,omitempty"`
	// 所属店铺
	ShopId int64 `json:"shop_id,omitempty"`
	// 所属商品
	GoodId int64 `json:"good_id,omitempty"`
	Title string `json:"title,omitempty"`
	// 商品属性名称
	AttrName string `json:"attr_name,omitempty"`
	// 商品属性值
	AttrValue string `json:"attr_value,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
	Price float64 `json:"price,omitempty"`
	ImgUrl string `json:"img_url,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	OffShelves bool `json:"off_shelves,omitempty"`
	StockShortage bool `json:"stock_shortage,omitempty"`
}
