/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormDomainGetMainReq struct {
	// 店铺编号
	ShopId int64 `json:"shop_id,omitempty"`
	// 是否为主店铺
	IsMain int32 `json:"is_main,omitempty"`
}
