/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetMemberGroupListByShopIdRes struct {
	Id int64 `json:"id,omitempty"`
	GroupName string `json:"group_name,omitempty"`
}
