/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormRoleDynamicMenu struct {
	// 菜单ID
	Id int64 `json:"id,omitempty"`
	// 父ID
	Pid int64 `json:"pid,omitempty"`
	// 菜单名称
	Name string `json:"name,omitempty"`
	// 菜单编码
	Code string `json:"code,omitempty"`
	// 路由地址
	Path string `json:"path,omitempty"`
	// 是否隐藏
	Hidden bool `json:"hidden,omitempty"`
	// 重定向
	Redirect string `json:"redirect,omitempty"`
	// 组件路径
	Component string `json:"component,omitempty"`
	// 暂时不知道干啥
	AlwaysShow bool `json:"alwaysShow,omitempty"`
	// 是否为外链（0是 1否）
	IsFrame string `json:"isFrame,omitempty"`
	Meta *XbuyAppFormAdminFormRoleDynamicMeta `json:"meta,omitempty"`
	// 子菜单
	Children []XbuyAppFormAdminFormRoleDynamicBase `json:"children,omitempty"`
}
