/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormDomainGetRes struct {
	// 域名编号
	DomainId int64 `json:"domain_id,omitempty"`
	// 店铺编号
	ShopId int64 `json:"shop_id,omitempty"`
	// 域名
	Domain string `json:"domain,omitempty"`
	// 域名类型
	Type_ string `json:"type,omitempty"`
	// 是否为主域名 0=否 1=是
	IsMain int32 `json:"is_main,omitempty"`
	// 谷歌认证ID
	GoogleVerifyId string `json:"google_verify_id,omitempty"`
	// bing认证ID
	BingVerifyId string `json:"bing_verify_id,omitempty"`
	// 百度认证ID
	BaiduVerifyId string `json:"baidu_verify_id,omitempty"`
}
