/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoFav struct {
	FavId int32 `json:"fav_id,omitempty"`
	MemberId int64 `json:"member_id,omitempty"`
	GoodId int64 `json:"good_id,omitempty"`
	SkuId int64 `json:"sku_id,omitempty"`
	CreateTime string `json:"create_time,omitempty"`
	Goods *XbuyAppModelEntityMallGoods `json:"goods,omitempty"`
	Sku *XbuyAppModelEntityMallSkus `json:"sku,omitempty"`
}
