/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormIsShopBlackListRes struct {
	// 是否在商店黑名单
	IsBlacklist bool `json:"is_blacklist,omitempty"`
}
