/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallAddress struct {
	// 地址编号
	AddressId int64 `json:"address_id,omitempty"`
	// 消费者编号
	MemberId int64 `json:"member_id,omitempty"`
	// 名
	FirstName string `json:"first_name,omitempty"`
	// 姓
	LastName string `json:"last_name,omitempty"`
	// 街道
	Street string `json:"street,omitempty"`
	// 详细地址
	Apartment string `json:"apartment,omitempty"`
	// 城市
	City string `json:"city,omitempty"`
	// 州/省
	State string `json:"state,omitempty"`
	// 邮政编码
	ZipCode string `json:"zip_code,omitempty"`
	// 国家
	Country string `json:"country,omitempty"`
	// 电话
	Phone string `json:"phone,omitempty"`
	// 是否默认 0=否 1=是
	IsDefault int32 `json:"is_default,omitempty"`
	// 排序
	Sort int32 `json:"sort,omitempty"`
}
