/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodInfoValuesAdd struct {
	// 标准类目参数Id
	InfoId int64 `json:"info_id,omitempty"`
	// 商品参数值
	Value string `json:"value,omitempty"`
}
