/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 读取仓库商品库存
type XbuyAppFormAdminFormWareHouseStockReadReq struct {
	WareHouseId int32 `json:"ware_house_id"`
	SkuId int64 `json:"sku_id"`
}
