/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormShopViewAddReq struct {
	// 视图id
	ViewId int64 `json:"view_id"`
	// 商店id
	ShopId int64 `json:"shop_id"`
	// 视图名称
	Name string `json:"name"`
	// 语言简写
	Language string `json:"language,omitempty"`
	// 币种
	Currency string `json:"currency,omitempty"`
}
