/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormExpressGetReq struct {
	// 快递公司ID
	ExpressId int64 `json:"express_id,omitempty"`
	// 快递公司编码
	LogisticsCode string `json:"logistics_code,omitempty"`
}
