/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoTargetWith struct {
	Id int32 `json:"id,omitempty"`
	// 折扣码ID
	CodeId int32 `json:"code_id,omitempty"`
	// 指定客户类型
	TargetUserType int32 `json:"target_user_type,omitempty"`
	// 用户等级
	Level int32 `json:"level,omitempty"`
	// 标签
	Label int32 `json:"label,omitempty"`
	// 用户ID
	MemberId int64 `json:"member_id,omitempty"`
	// 组别ID
	GroupId int32 `json:"group_id,omitempty"`
	// 组别名称
	TargetValue string `json:"target_value,omitempty"`
	MemberInfo *XbuyAppModelEntityMallMembers `json:"member_info,omitempty"`
	GroupInfo *XbuyAppModelEntityMallMemberGroups `json:"group_info,omitempty"`
	GradesInfo *XbuyAppModelEntityMallMemberGrades `json:"grades_info,omitempty"`
	TagsInfo *XbuyAppModelEntityMallMemberTags `json:"tags_info,omitempty"`
}
