/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormInputLogListModel struct {
	Id int64 `json:"id,omitempty"`
	// 应用id
	AppId string `json:"app_id,omitempty"`
	// 商户id
	MerchantId int32 `json:"merchant_id,omitempty"`
	// 用户id
	MemberId int32 `json:"member_id,omitempty"`
	// 提交类型
	Method string `json:"method,omitempty"`
	// 模块
	Module string `json:"module,omitempty"`
	// 提交url
	Url string `json:"url,omitempty"`
	// get数据
	GetData string `json:"get_data,omitempty"`
	// post数据
	PostData string `json:"post_data,omitempty"`
	// header数据
	HeaderData string `json:"header_data,omitempty"`
	// ip地址
	Ip string `json:"ip,omitempty"`
	// 省编码
	ProvinceId int32 `json:"province_id,omitempty"`
	// 市编码
	CityId int32 `json:"city_id,omitempty"`
	// 报错code
	ErrorCode int32 `json:"error_code,omitempty"`
	// 报错信息
	ErrorMsg string `json:"error_msg,omitempty"`
	// 报错日志
	ErrorData string `json:"error_data,omitempty"`
	// 对外id
	ReqId string `json:"req_id,omitempty"`
	// 响应时间
	Timestamp int32 `json:"timestamp,omitempty"`
	// UA信息
	UserAgent string `json:"user_agent,omitempty"`
	// 请求耗时
	TakeUpTime int64 `json:"take_up_time,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 修改时间
	UpdatedAt string `json:"updated_at,omitempty"`
	MemberName string `json:"member_name,omitempty"`
	Region string `json:"region,omitempty"`
}
