/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse20077Data struct {
	Id int64 `json:"id,omitempty"`
	GradeName string `json:"grade_name,omitempty"`
	Condition string `json:"condition,omitempty"`
	CreateTime string `json:"create_time,omitempty"`
	ShopId int64 `json:"shop_id,omitempty"`
}
