/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodInfoReq struct {
	// 商品ID
	GoodId int64 `json:"good_id"`
	// 视图ID
	ViewId int64 `json:"view_id,omitempty"`
}
