/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetMemberGroupRelationListByGroupIdReq struct {
	GroupId int64 `json:"GroupId"`
	ShopId int64 `json:"ShopId"`
}
