/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormMenuRoleListRes struct {
	// 菜单列表
	Menus []XbuyAppModelLabelTreeMenu `json:"menus,omitempty"`
	// 选择的菜单ID
	CheckedKeys []int64 `json:"checkedKeys,omitempty"`
}
