/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 创建仓库
type XbuyAppFormAdminFormWareHouseCreateReq struct {
	ShopId int64 `json:"shop_id"`
	Name string `json:"name"`
	AdminLastName string `json:"admin_last_name"`
	AdminFirstName string `json:"admin_first_name"`
	AdminPhone string `json:"admin_phone"`
	AdminEmail string `json:"admin_email"`
	CountryCode string `json:"country_code"`
	Province string `json:"province"`
	City string `json:"city"`
	Street string `json:"street"`
	Address string `json:"address"`
	ZipCode string `json:"zip_code"`
}
