/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormWareHouseStockPagingRes struct {
	Total int32 `json:"total,omitempty"`
	List []XbuyAppDaoSkuDetails `json:"List,omitempty"`
}
