/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormLoginTokenReq struct {
	// 用户名
	Username string `json:"username"`
	// 密码
	Password string `json:"password"`
	// 签名
	Sign string `json:"sign"`
	// 时间戳
	Time string `json:"time"`
	// 商户ID
	ShopId int64 `json:"shop_id"`
}
