/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormBindMemberToShopReq struct {
	// 会员ID
	Id int64 `json:"id"`
	// 商店ID
	ShopId int64 `json:"shopId"`
}
