/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetTaxRateByIdReq struct {
	Id int64 `json:"Id"`
	SkuId int64 `json:"SkuId"`
}
