/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallBillingAddress struct {
	// 表主键
	Id int32 `json:"id,omitempty"`
	// 所属订单
	OrderId string `json:"order_id,omitempty"`
	// 国家
	Country string `json:"country,omitempty"`
	// 省/州
	State string `json:"state,omitempty"`
	// 城市
	City string `json:"city,omitempty"`
	// 街道
	Street string `json:"street,omitempty"`
	// 详细地址
	Apartment string `json:"apartment,omitempty"`
	// 邮编
	ZipCode string `json:"zip_code,omitempty"`
	// 电话/手机号码
	Phone string `json:"phone,omitempty"`
	// 名
	FirstName string `json:"first_name,omitempty"`
	// 姓
	LastName string `json:"last_name,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
