/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyEtcAllowCustomMade struct {
	Enable bool `json:"enable,omitempty"`
	Title string `json:"title,omitempty"`
}
