/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormReadSkuTaxRes struct {
	ErrCode int32 `json:"err_code,omitempty"`
	ErrMsg string `json:"err_msg,omitempty"`
	Id int64 `json:"id,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	StateCode string `json:"state_code,omitempty"`
	TaxRate float64 `json:"tax_rate,omitempty"`
}
