/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallAftersaleItems struct {
	// 售后单号
	AfterSaleId string `json:"after_sale_id,omitempty"`
	// 所属商品标记
	GoodId int64 `json:"good_id,omitempty"`
	// 商品sku_id
	SkuId int64 `json:"sku_id,omitempty"`
	// 商品退款数量
	Num int32 `json:"num,omitempty"`
	// 商品退款金额
	Amount float64 `json:"amount,omitempty"`
	// 商品标题
	Title string `json:"title,omitempty"`
	// 商品图片地址
	ImgUrl string `json:"img_url,omitempty"`
	// 商品规格属性
	SkuProp string `json:"sku_prop,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
