/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200173Data struct {
	// 商品总数
	ItemTotal int32 `json:"item_total,omitempty"`
	// 上架商品总数
	ItemOnSaleTotal int32 `json:"item_on_sale_total,omitempty"`
	// 下架商品总数
	ItemOffSaleTotal int32 `json:"item_off_sale_total,omitempty"`
}
