/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200211Data struct {
	// 店铺配置列表
	Data map[string]string `json:"data,omitempty"`
}
