/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormSearchSkuInfoReq struct {
	// 所属门店
	ShopId int64 `json:"shop_id"`
	// sku_id
	SkuId int64 `json:"sku_id"`
}
