/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoChild struct {
	Name string `json:"name,omitempty"`
	SimpleSpeech string `json:"simple_speech,omitempty"`
	Key string `json:"key,omitempty"`
	Child []XbuyAppDaoChild `json:"child,omitempty"`
}
