/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 绑定邮箱
type XbuyAppFormAdminFormEmailBindReq struct {
	Emails string `json:"emails"`
}
