/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormExpress struct {
	ShopId string `json:"shop_id,omitempty"`
	CarryId string `json:"carry_id,omitempty"`
}
