/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoEffectWith struct {
	// 主键
	Id int32 `json:"id,omitempty"`
	// 折扣码ID
	CodeId int32 `json:"code_id,omitempty"`
	// 固定折扣适用商品类型
	EffectScopeType int32 `json:"effect_scope_type,omitempty"`
	// spu序号
	SpuSeq int64 `json:"spu_seq,omitempty"`
	// 产品ID
	GoodId int64 `json:"good_id,omitempty"`
	// sku序号
	SkuSeq int64 `json:"sku_seq,omitempty"`
	// skuId
	SkuId int64 `json:"sku_id,omitempty"`
	// 商品类别ID
	CategoryId int32 `json:"category_id,omitempty"`
	// 标签ID
	LabelId int32 `json:"label_id,omitempty"`
	// 默认分类名称
	DefaultSortationName string `json:"default_sortation_name,omitempty"`
	Goods *XbuyAppModelEntityMallGoods `json:"goods,omitempty"`
	Sku *XbuyAppModelEntityMallSkus `json:"sku,omitempty"`
	Cats *XbuyAppModelEntityMallCats `json:"cats,omitempty"`
}
