/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 订单物流列表
type XbuyAppFormMallFormOrderWaybillExpressReq struct {
	OrderId string `json:"order_id,omitempty"`
}
