/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormMemberUpdateAvatarReq struct {
	// 头像
	Avatar string `json:"avatar,omitempty"`
}
