/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyEtcTechnicalSupport struct {
	Type_ []string `json:"type,omitempty"`
	Title string `json:"title,omitempty"`
}
