/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormConfigViewRes struct {
	// 配置ID
	Id int64 `json:"id,omitempty"`
	// 参数名称
	Name string `json:"name,omitempty"`
	// 参数键名
	Key string `json:"key,omitempty"`
	// 参数键值
	Value string `json:"value,omitempty"`
	// 是否默认
	IsDefault string `json:"is_default,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt string `json:"updated_at,omitempty"`
}
