/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormApiFormReceiveBarCodeRateReq struct {
	Data string `json:"data"`
	Time string `json:"time"`
	Sign string `json:"sign"`
}
