/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200177Data struct {
	// 订单总数
	OrderTotal int32 `json:"order_total,omitempty"`
	// 本月订单总数
	OrderMonthTotal int32 `json:"order_month_total,omitempty"`
	// 待支付订单总数
	OrderWaitPayTotal int32 `json:"order_wait_pay_total,omitempty"`
	// 待发货订单总数
	OrderWaitSendTotal int32 `json:"order_wait_send_total,omitempty"`
	// 待收货订单总数
	OrderWaitReceiveTotal int32 `json:"order_wait_receive_total,omitempty"`
	// 退款订单总数
	OrderRefundTotal int32 `json:"order_refund_total,omitempty"`
	// 会员总数
	MemberTotal int32 `json:"member_total,omitempty"`
	// 支付总额
	PayTotal float64 `json:"pay_total,omitempty"`
	// 本月支付总额
	PayMonthTotal float64 `json:"pay_month_total,omitempty"`
}
