/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityAdminSynConfig struct {
	// 主键
	Id int32 `json:"id,omitempty"`
	// 店铺ID
	ShopId int64 `json:"shop_id,omitempty"`
	// 平台类型
	SynType string `json:"syn_type,omitempty"`
	// api地址
	ApiUrl string `json:"api_url,omitempty"`
	// key
	AppKey string `json:"app_key,omitempty"`
	// 秘钥
	AppSecret string `json:"app_secret,omitempty"`
	// token
	Token string `json:"token,omitempty"`
	// 外部接口所需json，可自行定义
	Data string `json:"data,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
