/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoOutputSkuInfo struct {
	// 类型编号
	PropId int64 `json:"prop_id,omitempty"`
	// 类型名称
	PropName string `json:"prop_name,omitempty"`
	// 类型图片
	ImgUrl string `json:"img_url,omitempty"`
	// 视图id
	ViewId int64 `json:"view_id,omitempty"`
	// 是否是ai
	Ai int32 `json:"ai,omitempty"`
	Values []XbuyAppDaoOutputValue `json:"values,omitempty"`
}
