/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallGoodInfos struct {
	// 标准类目参数ID
	InfoId int64 `json:"info_id,omitempty"`
	// 标准类目ID
	Cid int64 `json:"cid,omitempty"`
	// 类目名称
	Name string `json:"name,omitempty"`
	// 排序
	Sort string `json:"sort,omitempty"`
	// 父级pid
	Pid int64 `json:"pid,omitempty"`
}
