/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoExchangeRate struct {
	Currency string `json:"currency,omitempty"`
	Rate float64 `json:"rate,omitempty"`
}
