/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormInputAdminDeptListTreeDept struct {
	Id int64 `json:"id,omitempty"`
	Key int64 `json:"key,omitempty"`
	Pid int64 `json:"pid,omitempty"`
	Label string `json:"label,omitempty"`
	Title string `json:"title,omitempty"`
	Name string `json:"name,omitempty"`
	Type_ string `json:"type,omitempty"`
	Children []XbuyAppFormInputAdminDeptListTreeDept `json:"children,omitempty"`
}
