/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200209Data struct {
	// 支付方式列表
	List []XbuyAppFormMallFormPayWays `json:"list,omitempty"`
	HasIdentity bool `json:"has_identity,omitempty"`
	IdName string `json:"id_name,omitempty"`
	IdNumber string `json:"id_number,omitempty"`
}
