/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallService struct {
	// 增值服务ID
	ServiceId int64 `json:"service_id,omitempty"`
	// 门店ID
	ShopId int64 `json:"shop_id,omitempty"`
	// 增值服务名称
	ServiceName string `json:"service_name,omitempty"`
	// 增值服务描述，用于提供详细的说明和介绍
	Description string `json:"description,omitempty"`
	// 增值服务价格
	Price float64 `json:"price,omitempty"`
	// 是否为店铺级服务 默认1 1=全店商品 2=单品 3=单分类 4=公共分类
	Type_ int32 `json:"type,omitempty"`
	// 增值服务状态 默认1 1=启用 2=禁止
	Status int32 `json:"status,omitempty"`
	// 数量是否叠加 默认1 1=不叠加 1种商品收一次钱 2=叠加 一个sku收一次钱
	Multiple int32 `json:"multiple,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime string `json:"update_time,omitempty"`
}
