/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoSkuAttr struct {
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
