/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200186Data struct {
	WareHouseId int32 `json:"ware_house_id,omitempty"`
	SkuId int64 `json:"sku_id,omitempty"`
	StockQuantity int32 `json:"stock_quantity,omitempty"`
}
