/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200190Data struct {
	// 收货地址ID
	AddressId int32 `json:"address_id,omitempty"`
}
