/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormStockDetails struct {
	SkuId int64 `json:"sku_id"`
	StockQuantity int32 `json:"stock_quantity"`
	WarehouseId int32 `json:"warehouse_id"`
}
