/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoBenefitWith struct {
	// 主键
	Id int32 `json:"id,omitempty"`
	// 折扣码ID
	CodeId int32 `json:"code_id,omitempty"`
	// 优惠类型范围 1.指定商品；2.指定商品分类；3.指定商品款式(Sku)
	BenefitScopeType int32 `json:"benefit_scope_type,omitempty"`
	// 商品ID
	GoodId int64 `json:"good_id,omitempty"`
	// SkuId
	SkuId int64 `json:"sku_id,omitempty"`
	// 分类ID
	TargetId int64 `json:"target_id,omitempty"`
	// 分类名称
	TargetName string `json:"target_name,omitempty"`
	Goods *XbuyAppModelEntityMallGoods `json:"goods,omitempty"`
	Sku *XbuyAppModelEntityMallSkus `json:"sku,omitempty"`
}
