/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetSkuStockReq struct {
	ShopId int64 `json:"shop_id"`
	SkuId int64 `json:"sku_id"`
}
