/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoBenefitCode struct {
	// 折扣码主键
	Id int32 `json:"id,omitempty"`
	// 店铺ID
	ShopId int64 `json:"shop_id,omitempty"`
	// 活动名称
	ActivityName string `json:"activity_name,omitempty"`
	// 活动描述
	ActivityDesc string `json:"activity_desc,omitempty"`
	// 折扣码
	PromotionCode string `json:"promotion_code,omitempty"`
	// 折扣码类型  1百分比折扣（满100打9折）  2固定金额（满100减10元）  3买X送Y（买2件送1件）  4免运费（满3件免运费）
	BenefitType int32 `json:"benefit_type,omitempty"`
	// 优惠条件 {\"type\":\"\",\"minThreshold\":\"\"}   满金额类型以分作为单位存储
	BenefitEvent string `json:"benefit_event,omitempty"`
	// 是否指定客户  0否  1是
	TargetUserType int32 `json:"target_user_type,omitempty"`
	// 活动状态  0关闭  1开启
	ActivityStatus int32 `json:"activity_status,omitempty"`
	// 允许与自动折扣叠加使用  0 = false,  1 = true
	OverlayAutoDiscounts int32 `json:"overlay_auto_discounts,omitempty"`
	// 允许与其他折扣码叠加使用  0 = false,  1 = true
	OverlayDiscountCode int32 `json:"overlay_discount_code,omitempty"`
	// 免运费金额上限  -1为不限制，正数为限制
	PrerequisiteShippingPriceRange int32 `json:"prerequisite_shipping_price_range,omitempty"`
	// 设置每笔订单最高优惠金额  -1为不限制，正数为限制
	MaxBenefitAmount int32 `json:"max_benefit_amount,omitempty"`
	// 国家免运费  all = 所有国家都免，entitled = 部分国家免运费
	EntitledCountryTargetSelection string `json:"entitled_country_target_selection,omitempty"`
	// 免运费国家ID列表
	EntitledCountryIdList string `json:"entitled_country_id_list,omitempty"`
	// 订单限制，0 = false, 1 = true
	OrderUseLimit int32 `json:"order_use_limit,omitempty"`
	// 折扣码共能使用次数
	PublishNum int32 `json:"publish_num,omitempty"`
	// 每人可用次数
	AcquirePerUserLimit int32 `json:"acquire_per_user_limit,omitempty"`
	// 商品详情页折扣码显示, 0 = false, 1 = true
	DiscountCodeDisplay int32 `json:"discount_code_display,omitempty"`
	// 满送类型设置每个订单的最大使用次数   -1 = 不限制，正数 = 限制
	MaxAccumulateNum int32 `json:"max_accumulate_num,omitempty"`
	// 优惠类型范围  1.指定商品；2.指定商品分类；3.指定商品款式(Sku)
	BenefitScopeType int32 `json:"benefit_scope_type,omitempty"`
	// 固定折扣适用商品类型   0所有商品；1.指定商品；2.指定商品分类；3.指定商品款式(Sku)
	EffectScopeType int32 `json:"effect_scope_type,omitempty"`
	// 开始时间
	StartTime string `json:"start_time,omitempty"`
	// 结束时间
	EndTime string `json:"end_time,omitempty"`
	BenefitCondition *XbuyAppModelEntityMallBenefitCondition `json:"benefit_condition,omitempty"`
	EnvCustomInfo *XbuyAppModelEntityMallBenefitEnvCustomInfo `json:"env_custom_info,omitempty"`
	BenefitScopeGoodsList []XbuyAppDaoBenefitWith `json:"benefit_scope_goods_list,omitempty"`
	EffectScopeGoodsList []XbuyAppDaoEffectWith `json:"effect_scope_goods_list,omitempty"`
	TargetUserInfoList []XbuyAppDaoTargetWith `json:"target_user_info_list,omitempty"`
}
