/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormServiceAddReq struct {
	// 服务ID
	ServiceId int64 `json:"service_id,omitempty"`
	// 服务名称
	ServiceName string `json:"service_name"`
	// 服务描述
	Description string `json:"description,omitempty"`
	// 服务价格
	Price float64 `json:"price"`
	// 服务类型
	Type_ int32 `json:"type"`
	// 是否叠加
	Multiple int32 `json:"multiple"`
	// 服务状态
	Status int32 `json:"status"`
	// 商品ID集合
	GoodsIds []int64 `json:"goods_ids,omitempty"`
	// 商品分类ID集合
	CategoryIds []int64 `json:"category_ids,omitempty"`
	// 公共分类ID集合
	ScatIds []int64 `json:"scat_ids,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime string `json:"update_time,omitempty"`
}
