/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200157Data struct {
	// 视图id
	ViewId int64 `json:"view_id,omitempty"`
	// 商店id
	ShopId int64 `json:"shop_id,omitempty"`
	// 视图名称
	Name string `json:"name,omitempty"`
	// 语言简写
	Language string `json:"language,omitempty"`
	// 币种
	Currency string `json:"currency,omitempty"`
	// 自动翻译，0不自动翻译，1自动翻译
	AutoTrans int32 `json:"auto_trans,omitempty"`
	// 1=默认
	IsDefault int32 `json:"is_default,omitempty"`
}
