/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormUploadFileRes struct {
	FileId int64 `json:"file_id,omitempty"`
	FilePath string `json:"file_path,omitempty"`
}
