/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 邮件服务设置
type XbuyAppFormAdminFormEmailSettingReq struct {
	SmtpHost string `json:"smtp_host,omitempty"`
	SmtpPort int32 `json:"smtp_port,omitempty"`
	ImapHost string `json:"imap_host,omitempty"`
	ImapPort int32 `json:"imap_port,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}
