/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 增加评论
type XbuyAppFormMallFormReviewAddReq struct {
	ReviewId int32 `json:"review_id,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	GoodsId int64 `json:"goods_id,omitempty"`
	SkuId int64 `json:"sku_id,omitempty"`
	Grade int32 `json:"grade,omitempty"`
	ReviewContent string `json:"review_content,omitempty"`
	// 创建时间
	CreateTime string `json:"create_time,omitempty"`
}
