/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse20060Data struct {
	// 数据列表
	List []XbuyAppModelEntityMallConfigs `json:"list,omitempty"`
}
