/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 读取仓库列表
type XbuyAppFormAdminFormWareHouseReadReq struct {
}
