/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormCatsList struct {
	// 分类ID
	CatId int64 `json:"cat_id,omitempty"`
	// 分类名称
	Name string `json:"name,omitempty"`
}
