/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormApiFormReceiveExamineReq struct {
	// base64数据
	Data string `json:"data"`
	// 时间
	Time string `json:"time"`
	// 签名
	Sign string `json:"sign"`
}
