/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200212Data struct {
	// 店铺列表
	Shops []XbuyAppModelEntityMallShops `json:"shops,omitempty"`
}
