/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormGetBindShopRes struct {
	// 店铺列表
	List []XbuyAppModelEntityAdminSubmemberShop `json:"list,omitempty"`
}
