/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormDictDataEditReq struct {
	// 字典编码
	Id int64 `json:"id,omitempty"`
	// 字典标签
	Label string `json:"label,omitempty"`
	// 字典键值
	Value string `json:"value,omitempty"`
	// 字典类型
	Type_ string `json:"type,omitempty"`
	// 表格回显样式
	ListClass string `json:"list_class,omitempty"`
	// 是否默认
	IsDefault string `json:"is_default,omitempty"`
	// 字典排序
	Sort int32 `json:"sort,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt string `json:"updated_at,omitempty"`
}
