/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormAdminFormBindMemberGradeRes struct {
	MemberId int64 `json:"member_id,omitempty"`
	GradeId int64 `json:"grade_id,omitempty"`
	CreateTime string `json:"create_time,omitempty"`
	IsAuto int64 `json:"is_auto,omitempty"`
}
