/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormMallFormArticleNewListReq struct {
	// 当前页码
	Page int32 `json:"page,omitempty"`
	// 每页数量
	Limit int32 `json:"limit,omitempty"`
	ShopId int64 `json:"shop_id,omitempty"`
	ViewId int64 `json:"view_id,omitempty"`
	CatId int64 `json:"cat_id,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ int32 `json:"type,omitempty"`
}
