/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 修改优先发货策略
type XbuyAppFormAdminFormPriorityPolicyUpdateReq struct {
	WeightSetting []XbuyAppFormAdminFormWeightSetting `json:"weight_setting"`
}
