/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormCatSubAddReq struct {
	// 类目编号
	CatId int64 `json:"cat_id"`
	// 商店编号
	ShopId int64 `json:"shop_id"`
	// 视图Id
	ViewId int64 `json:"view_id"`
	// 名称
	Name string `json:"name,omitempty"`
	// 排序权重
	Weight int32 `json:"weight,omitempty"`
	// 图标
	ImageUrl string `json:"image_url,omitempty"`
	// 是否启用ai翻译
	Ai int32 `json:"ai,omitempty"`
}
