/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200104Data struct {
	// ID
	Id int64 `json:"id,omitempty"`
	// 标签ID
	TagId int64 `json:"tag_id,omitempty"`
	// 会员ID
	MemberId int64 `json:"member_id,omitempty"`
	CreateTime *ModelInterface `json:"create_time,omitempty"`
}
