/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormReadSkuTaxReq struct {
	SkuId int64 `json:"SkuId"`
	CountryCode string `json:"CountryCode,omitempty"`
}
