/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200192Data struct {
	// 商城底部菜单列表
	List map[string][]XbuyAppModelEntityMallArticlesSub `json:"list,omitempty"`
}
