/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppModelEntityMallMemberGrades struct {
	Id int64 `json:"id,omitempty"`
	// 等级名字
	GradeName string `json:"grade_name,omitempty"`
	// 等级条件
	GradeCondition string `json:"grade_condition,omitempty"`
	CreateTime string `json:"create_time,omitempty"`
	ShopId int64 `json:"shop_id,omitempty"`
}
