/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200127Data struct {
	OrderId string `json:"order_id,omitempty"`
	ShipTime string `json:"ship_time,omitempty"`
	Status string `json:"status,omitempty"`
}
