/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type InlineResponse200135Data struct {
	// 运费方式编号
	CarryId int64 `json:"carry_id,omitempty"`
}
