/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormUpdateBindShopReq struct {
	MemberId int64 `json:"member_id,omitempty"`
	ShopIds []int64 `json:"shop_ids,omitempty"`
}
