/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGoodInfoValueDeleteOneReq struct {
	// 商品Id
	GoodId int64 `json:"good_id"`
	// 类目参数Id
	InfoId int64 `json:"info_id"`
}
