/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 数据集
type XbuyAppFormApiFormLoginCheckRes struct {
	// 是否验证码
	IsValidCodeLogin bool `json:"isValidCodeLogin,omitempty"`
	// 消息
	Message string `json:"message,omitempty"`
	// 响应
	Result string `json:"result,omitempty"`
}
