/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppDaoRows struct {
	Clicks float64 `json:"clicks,omitempty"`
	Ctr float64 `json:"ctr,omitempty"`
	Impressions float64 `json:"impressions,omitempty"`
	Keys []string `json:"keys,omitempty"`
	Position float64 `json:"position,omitempty"`
}
