/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type XbuyAppFormAdminFormGetMemberGroupRelationListByGroupIdNotBindRes struct {
	MemberId int64 `json:"member_id,omitempty"`
	Nick string `json:"nick,omitempty"`
	Email string `json:"email,omitempty"`
}
