/*
 * xbuy
 *
 * xbuy大黄蜂买手项目
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 更新仓库
type XbuyAppFormAdminFormWareHouseUpdateReq struct {
	ShopId int64 `json:"shop_id"`
	WareHouseId int32 `json:"ware_house_id"`
	Name string `json:"name,omitempty"`
	Status int32 `json:"status,omitempty"`
	AdminLastName string `json:"admin_last_name,omitempty"`
	AdminFirstName string `json:"admin_first_name,omitempty"`
	AdminPhone string `json:"admin_phone,omitempty"`
	AdminEmail string `json:"admin_email,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	Province string `json:"province,omitempty"`
	City string `json:"city,omitempty"`
	Street string `json:"street,omitempty"`
	Address string `json:"address,omitempty"`
	ZipCode string `json:"zip_code,omitempty"`
}
